### ISSUE TITLE
delete input/output parameter in PipelineDevelopperView

### ISSUE THREAD

**Issue by Hboni** [populse/capsul#137]
When I use the `PipelineDevelopperView`, when I export an input/output parameter by mistake, it goes in _inputs/outputs_ box, but I cannot remove it from this box (For example in case of wanting to branch the output onto another process and not directly in outputs).

I tried to save the pipeline and open it, and the unwanted parameters in _inputs/outputs_ box were removed.

**Comment by denisri** [comment]
You also have an option "remove plug" when clicking on the plug. Does it work for you ?
(well it's still a bug here but the remove plug option may offer a workaround in the meantime)

**Comment by Hboni** [comment]
Oh yeah, I didn't click exactly on the plug, It works for me, thanks !
