### ISSUE TITLE
Running "bv_maker doc" creates an untracked file in the Git repository (capsul_tutorial.ipynb)

### ISSUE THREAD

**Issue by ylep** [populse/capsul#168]
Running `bv_maker doc` creates an untracked file in the Git repository (`doc/source/tutorial/capsul_tutorial.ipynb`). We should:

- either, generate this file somewhere else (in a temporary location?)
- or, add it to `.gitignore` to stop the Git repository from being shown as dirty.

**Comment by denisri** [comment]
The 1st solution is clearly better but it was a bit difficult to implement simply (1)
The 2nd solution is the simplest right now.

(1) The notebooks are processed using python 2/3 then used by the nbsphinx module to actually generate docs. Thus it expects them in the source directory. To be completely clean, we would need to copy/symlink recursively the endire doc source tree in the build directory before running sphinx from there, and not from the actual source tree. I think this is done in one or two of our projects, but I don't even remember which ones.
