### ISSUE TITLE
Handling of Undefined values in workflows

### ISSUE THREAD

**Issue by denisri** [populse/capsul#171]
For now all process values, including `Undefined` values, are set in jobs parameters when converting pipelines into workflows. Then parameters are set in commandline arguments, or in a parameters file. Thus all values are hard-coded at the time of workflow building. This is OK in most cases. But Nipype may use global configuration settings (see `nipype.interfaces.spm.SPMCommand.set_mlab_paths` or `nipype.interfaces.matlab.MatlabCommand.set_mlab_paths`) which will change default values of processes instantiated later. To be working, this needs the corresponding parameters **not to be set** by parameters given in the workflow which are left to `Undefined` values, because currently the `Undefined` values are forced and thus overwrite the configuration settings.
The underlying question is: what does `Undefined` mean, and does it always mean the same ?
* it is normally "only" a default value for parameters which are optional and not set
* are there cases where we really want to force an `Undefined` value on a process which, by default, has a *different* value ? Here it's probably not just a default value, but means something else, like "don't use a default feature"...?

If there are no situations for the 2nd case, then we should simply ignore parameters with `Undefined` values when passing them to the jobs. But if this situation actually exists, we cannot do that.
I can't think of such a case, but I don't want do do a mistake and break things...
What do you think ?

**Comment by servoz** [comment]
I have so far used and think Undefined only in the case 1/ ...well ... I think :-)

**Comment by sapetnioc** [comment]
If we really need to mean something, we should not use Undefined value.

>
