### ISSUE TITLE
Remove StudyConfig class

### ISSUE THREAD

**Issue by sapetnioc** [populse/capsul#178]
This configuration class is obsolete and is meant to disappear

**Comment by sapetnioc** [comment]
What about the completion engines that are defined in StudyConfig ? Should they be removed to be reintroduced later in CapsulEngine ?

**Comment by denisri** [comment]
I usually do the contrary: reimplement before removing, but yes I guess they have to be moved to CapsulEngine.

**Comment by sapetnioc** [comment]
In this case, it is difficult to keep both because StudyConfig is removed.

**Comment by denisri** [comment]
Maybe I didn't understand what you were talking about, I was just saying that we might want to reimplement things (like config completion or other) in CapsulEngine before removing StudyConfig, but perhaps it's already done.

**Comment by sapetnioc** [comment]
This issue is replaced by #198
