### ISSUE TITLE
Strange behaviour with the in_out_pipeline_nodes branch

### ISSUE THREAD

**Issue by servoz** [populse/capsul#186]
I just started to work on the input/output gnodes.

Contrary to what is currently the case we would like:
- 1 if the input and output gnodes have no more plugs, they should no longer appear (for the moment there is one empty gnode).
- 2 it is possible to delete the input and output gnodes (for the moment this is not possible). If we delete them, the existing links should of course disappear.

I have started to work on point 1 in the in_out_pipeline_nodes branch.
The change is very simple, just 2 lines in the capsul.qt_gui.widgets.pipeline_developer_view.PipelineScene._update_regular_pipeline() method. The rest of the changes are just for introspection and will disappear at the end of this work.

The problem I see is that the result is erratic... Sometimes the gnode disappears, sometimes not ... I've been trying to figure it out without success ... If someone can take a look, maybe I'm forgetting something. I'm not a capsul expert yet!

I'll start working on this ticket again a little later. Any suggestions are welcome!

**Comment by denisri** [comment]
After another modif in popules_mia (populse/populse_mia@f0092894ab72496926c9fcc50e224b6d351ecfbc), deleting the pipeline input or output nodes seems to work.

**Comment by servoz** [comment]
Hooray!!!!!!
I have a lot to catch up on, but I'll get to it ASAP!!!.

**Comment by servoz** [comment]
Oh yes !!! it's working ! 
I think I can delete the in_out_pipeline_nodes branch which is now useless?
It remains to manage the undo/redo which is not for now managed and makes a Mia crash, but we will see that in populse_mia side.
I think point 2 may also be comfortable for the user (if we want to delete all entries at once, rather than doing it by hand one by one). When do you think?
If we decide to do it. I'm closing this ticket and opening one on this topic on the populse_mia side (so we don't forget to work on it, but no time to deal with it at the moment).
 If we don't decide to do it, I just close this ticket ... and that's it :-)))

**Comment by denisri** [comment]
> I think I can delete the in_out_pipeline_nodes branch which is now useless?

I guess so, yes.

> I think point 2 may also be comfortable for the user (if we want to delete all entries at once, rather than doing it by hand one by one). What do you think?

Point 2 is already working, but it's not in the right-click menu (I have forgotten to add it, I will do so). If you select the input or output node and press "del" on the keyboard, then it's actually deleted (no confirmation asked...)

**Comment by servoz** [comment]
You are wonderful!
I like to end the week by closing tickets !!!!
