### ISSUE TITLE
Memory leak when iterating a renamed pipeline

### ISSUE THREAD

**Issue by LStruber** [populse/capsul#196]
When calling `release_pipeline` function of `pipeline_developper_view.py`, a new `PipelineScene` is created without properly deleting the former. Indeed, the `__del__()` method of `PipelineScene` is not called.

This can lead to issues in MIA (e.g.  populse/populse_mia#247). For now crashes have been prevented by manually deleting the scene in `release_pipeline` function (commit 793f1d26f157a2b1decc495ded9202f3800484ef) but the memory leak remains (and could lead to other issues ?).

**Comment by denisri** [comment]
I have spent some time on this, but without success.
deleting a `PipelineDevelopperView` actually deletes the `PipelineScene`
calling `PipelineDevelopperView.release_pipeline()` does not delete it
When calling several times `PipelineDevelopperView.set_pipeline()`, as many new `PipelineScene` are created, but none is deleted.
Then when deleting the `PipelineDevelopperView`, all `PipelineScene` instances are deleted. Thus something keeps references to all `PipelineScene` instances in the `PipelineDevelopperView` as long as it lives, but I can't find where.
```
objgraph.show_backrefs(objgraph.by_type('PipelineScene')[0])
```
displays a reference link between `PipelineDevelopperView` and `PipelineScene`, but without a variable name so I don't know where this link is. Maybe in sip/PyQt...

**Comment by denisri** [comment]
OK I have found a problem in PyQt ownership management, and could force it using sip.transferback(). I keep the ticket open until you check if it really fixes the problem for you, @LStruber . Close it again if it is OK.
