### ISSUE TITLE
rework and fix path generation system in v3

### ISSUE THREAD

**Issue by denisri** [populse/capsul#240]
The path generation system works for "regular" pipelines and for iterations over pipelines with a "simple" schema, but does not work for iterations over pipelines with a complex schema: it does not dig into iterated pipelines schemas.
We must rework the system, and have a simple test case for it (simpler than FakeMorphologist)

**Comment by sapetnioc** [comment]
The new path generation system appears to work for FakeMorphologist. It has not been intensively tested but I think it is enough to close this issue.
