### ISSUE TITLE
Drop AppVeyor CI

### ISSUE THREAD

**Issue by sapetnioc** [populse/capsul#262]
3.0 tests are using GitHub actions to allow easy installation and running of a Redis server. I would not know how to do the same with AppVeyor that is running Windows. To avoid to maintain two CI systems, we could move everything to Github actions.

**Comment by sapetnioc** [comment]
Tests ins v3.0 are now using pytest and GitHub actions.
AppVeyor tests are triggered for all branches and are reported as failure for pull requests in v3.0.
Therefore, I will try to switch from AppVeyor to GitHub actions for master branch too.

**Comment by denisri** [comment]
OK.

**Comment by sapetnioc** [comment]
Master branch is now tested 9 times: [Python 3.9, Python 3.10, Python 3.11] * [Linux, Mac, Windows] with Github actions.
